name: microservices

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=device_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      app-network:
      
  telemetries:
    build:
      context: telemetries
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    networks:
      app-network:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/device_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093  

  devices:
    build:
      context: Devices
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8082:8082'
    networks:
      app-network:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/device_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093    
      
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      app-network:

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    networks:
      app-network:
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper   

  swagger-ui:
    container_name: swagger-ui
    image: dh-mirror.gitverse.ru/swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    networks:
      app-network:
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./Sprint3_Task_1_2_3_4/src/1-4_Api.yaml:/openapi.yaml
      
networks:
  app-network:
    driver: bridge

