@startuml

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Remote manage warm in home

top to bottom direction

Person(User, "User", "A user of the fitness club system")
Person(Admin, "Admin", "An administrator managing the system")
System(FitLifeSystem, "Manage warm and monitoring temperature", "Manage devices")

Container_Boundary(FitLifeSystem, "FitLife System") {
  Container(ApiGateway, "ApiGateway", "Java", "Allows users to manage their membership")
  Container(ManageWarm, "ManageWarmService", "Java", "Allows users to manage their membership")
  Container(MonitoringTemperature, "MonitoringTemperatureService", "Java", "Processes payments")
  Container(DataBus, "DataBus", "Kafka", "Allows users to manage their membership")
  Container(Database, "Database", "PostgreSQL", "Stores user data and schedules")
}

System_Ext(ApiSensors, "ApiSensors", "External API for fitness data integration")

Rel(Admin, ApiGateway,"Manages the system")
Rel(User, ApiGateway, "Uses the system")
Rel(ApiGateway, MonitoringTemperature,"Manages the system")
Rel(ApiGateway, ManageWarm,"Manages the system")
Rel(MonitoringTemperature, DataBus,"Processes payment requests")
Rel(ManageWarm,DataBus,"Reads/Writes user data")
Rel(DataBus, Database, "Processes payment requests")
Rel(MonitoringTemperature,ApiSensors,"Fetches fitness data")

@enduml